Adding RUG::B meeting
jsconf/wwwtf.berlin pull request #74
Opened 2017-04-26 16:31 UTC by halfbyte

As RUG::B will happen in the wwwtf week by chance, I thought it might be worthwhile to add it to this list.

This has been cleared with @pragtob, who's the current organizer, on twitter.

2017-04-26 16:36 UTC, PragTob commented
Not sure what the possible values are here, but you don't really need to rsvp - we don't check that. It's more an optional nice to know thing :D 

thanks @halfbyte !

2017-04-26 16:42 UTC, halfbyte commented
@PragTob Made the event "free". Didn't really think about it first, tbqh.

My pleasure :)

2017-04-26 21:44 UTC, hagenburger requested changes
Thanks, @halfbyte :)

2017-04-26 21:44 UTC, hagenburger commented on _posts/2017-05-04-rug-b-meetup.mdown
> +title:  "Ruby Usergroup Berlin May Meetup"
The CI department comments: it should be written “Ruby User Group Berlin” ;)

2017-04-27 07:50 UTC, merged

2017-04-27 07:55 UTC, rmehner commented
Welcome my Ruby friends! :)

2017-04-27 11:32 UTC, filtercake commented
![img_5449](https://cloud.githubusercontent.com/assets/170145/25481483/a916ab24-2b4d-11e7-8fa3-fdb1679edce0.PNG)

Sorry, cannot inspect rn, screenshot from iphone 6s @ 10.1.1

2017-04-27 11:36 UTC, halfbyte commented
Yes, the text also is too long for the desktop view. I didn't write that text, though.

No one was using that type of ticket-type before, I guess. I could venture a fix (replace the text with only "Free" would work, I guess), but this is more of a general issue with the wwwtf site.

Quick fix without changing something at the template level would be to switch back to RSVP. 

Any Idea what would be best, @rmehner (paging you as you have merged this)

2017-04-27 11:42 UTC, rmehner commented
We all don't have so much time on our hands, so "replace the text with only "Free" would work" is probably good :)

2017-04-27 11:52 UTC, halfbyte commented
@rmehner See #75. 

Thanks all!